<a href="https://colab.research.google.com/github/savioratharv/Compute_tasks/blob/main/Atharv_Patawar_A5_Task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Q1 Import and explore the data
Dataset Link: https://drive.google.com/file/d/1tPHOMKD_ef-j8MuynCn2fSpbrL11-J1l/view?usp=sharing

In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("pulsar.txt", sep=",")

In [4]:
df

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,121.156250,48.372971,0.375485,-0.013165,3.168896,18.399367,7.449874,65.159298,0.0
1,76.968750,36.175557,0.712898,3.388719,2.399666,17.570997,9.414652,102.722975,0.0
2,130.585938,53.229534,0.133408,-0.297242,2.743311,22.362553,8.508364,74.031324,0.0
3,156.398438,48.865942,-0.215989,-0.171294,17.471572,NaN,2.958066,7.197842,0.0
4,84.804688,36.117659,0.825013,3.274125,2.790134,20.618009,8.405008,76.291128,0.0
...,...,...,...,...,...,...,...,...,...
12523,124.312500,53.179053,-0.012418,-0.556021,7.186455,29.308266,4.531382,21.725143,0.0
12524,115.617188,46.784600,0.218177,0.226757,6.140468,NaN,5.732201,34.357283,0.0
12525,116.031250,43.213846,0.663456,0.433088,0.785117,11.628149,17.055215,312.204325,0.0
12526,135.664062,49.933749,-0.089940,-0.226726,3.859532,21.501505,7.398395,62.334018,0.0
12527,120.726562,50.472256,0.346178,0.184797,0.769231,11.792603,17.662222,329.548016,0.0

In [6]:
df.isnull().sum()

 Mean of the integrated profile                     0
 Standard deviation of the integrated profile       0
 Excess kurtosis of the integrated profile       1735
 Skewness of the integrated profile                 0
 Mean of the DM-SNR curve                           0
 Standard deviation of the DM-SNR curve          1178
 Excess kurtosis of the DM-SNR curve                0
 Skewness of the DM-SNR curve                     625
target_class                                        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12528 entries, 0 to 12527
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0    Mean of the integrated profile                12528 non-null  float64
 1    Standard deviation of the integrated profile  12528 non-null  float64
 2    Excess kurtosis of the integrated profile     10793 non-null  float64
 3    Skewness of the integrated profile            12528 non-null  float64
 4    Mean of the DM-SNR curve                      12528 non-null  float64
 5    Standard deviation of the DM-SNR curve        11350 non-null  float64
 6    Excess kurtosis of the DM-SNR curve           12528 non-null  float64
 7    Skewness of the DM-SNR curve                  11903 non-null  float64
 8   target_class                                   12528 non-null  float64
dtypes: float64(9)
memory usage: 881.0 KB

##Q2 Carry out data pre-processing

In [8]:
df.dropna(axis=0,inplace=True)

##Q4 Split the data in traina and test set

In [10]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

##Q3 Scale the data using Standard Scaler

####Q3a According to you, why is scaling important in SVM? What are the different methods for scaling the data available in sklearn.preprocessing?

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

##Q5 Implement SVM

Different types of kernels in SVM:
https://www.kaggle.com/discussions/questions-and-answers/326336

###Q5a Linear SVM

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
param_grid = {'C': [0.1,1, 10, 100]} 
grid_search = GridSearchCV(estimator = classifier,
                           scoring='f1_micro',
                           param_grid = param_grid,
                           refit=2,
                           verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ..............................................C=0.1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ................................................C=1; total time=   0.1s
[CV] END ...............................................C=10; total time=   0.3s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ..............................................C=100; total time=   1.0s
[CV] END ..............................................C=100; total time=   1.0s
[CV] END ..............................................C=100; total time=   0.9s
[CV] END ..............................................C=100; total time=   0.7s
[CV] END ..............................................C=100; total time=   0.9s

GridSearchCV(estimator=SVC(kernel='linear', random_state=0),
             param_grid={'C': [0.1, 1, 10, 100]}, refit=2, scoring='f1_micro',
             verbose=2)

In [18]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.151359,0.115843,0.020865,0.010866,0.1,{'C': 0.1},0.977714,0.982746,0.978433,0.974119,0.974101,0.977423,0.003206,4
1,0.078607,0.002772,0.012064,0.000817,1,{'C': 1},0.979152,0.984184,0.977714,0.976995,0.975540,0.978717,0.002971,3
2,0.203979,0.024578,0.012117,0.001268,10,{'C': 10},0.979152,0.983465,0.978433,0.976995,0.975540,0.978717,0.002679,2
3,0.903651,0.097746,0.011395,0.000303,100,{'C': 100},0.979871,0.983465,0.978433,0.976995,0.975540,0.978861,0.002717,1

###Q5b Polynomial Kernel

Apply Linear SVM for degrees = [1,2,3,4,5], predict for the test set and check f1 score for each of the degrees. State the best degree.

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 0)
param_grid = {'degree': [1,2,3,4,5]} 
grid_search = GridSearchCV(estimator = classifier,
                           scoring='f1_micro',
                           param_grid = param_grid,
                           refit=2,
                           verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=1; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=2; total time=   0.1s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=3; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=4; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.2s
[CV] END ...........................................degree=4; total time=   0.3s
[CV] END ...........................................degree=5; total time=   0.6s
[CV] END ...........................................degree=5; total time=   1.4s
[CV] END ...........................................degree=5; total time=   0.5s
[CV] END ...........................................degree=5; total time=   0.3s
[CV] END ...........................................degree=5; total time=   0.4s

GridSearchCV(estimator=SVC(kernel='poly', random_state=0),
             param_grid={'degree': [1, 2, 3, 4, 5]}, refit=2,
             scoring='f1_micro', verbose=2)

In [20]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_degree,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.080357,0.008224,0.013863,0.001184,1,{'degree': 1},0.977714,0.983465,0.978433,0.974838,0.974820,0.977854,0.003167,1
1,0.101765,0.004286,0.014647,0.000411,2,{'degree': 2},0.974838,0.976995,0.974119,0.971244,0.971942,0.973828,0.002067,3
2,0.173749,0.015794,0.014137,0.001415,3,{'degree': 3},0.976995,0.979871,0.976276,0.974119,0.974820,0.976416,0.002006,2
3,0.236586,0.031382,0.015446,0.000879,4,{'degree': 4},0.971963,0.976276,0.973400,0.972682,0.972662,0.973397,0.001510,4
4,0.609957,0.403887,0.024691,0.021127,5,{'degree': 5},0.971963,0.976276,0.970525,0.973400,0.970504,0.972534,0.002156,5

###Q5c Sigmoid Kernel

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0)
param_grid = {'C': [0.1, 1, 10, 100, 1000]} 
grid_search = GridSearchCV(estimator = classifier,
                           scoring='f1_micro',
                           param_grid = param_grid,
                           refit=2,
                           verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ..............................................C=0.1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ................................................C=1; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ...............................................C=10; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s
[CV] END .............................................C=1000; total time=   0.4s

GridSearchCV(estimator=SVC(kernel='sigmoid', random_state=0),
             param_grid={'C': [0.1, 1, 10, 100, 1000]}, refit=2,
             scoring='f1_micro', verbose=2)

In [22]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.352181,0.010508,0.076017,0.002613,0.1,{'C': 0.1},0.879224,0.882818,0.867721,0.872753,0.869065,0.874316,0.005829,1
1,0.341135,0.014646,0.070055,0.001557,1,{'C': 1},0.874191,0.882099,0.864845,0.865564,0.862590,0.869858,0.007280,2
2,0.334204,0.020239,0.070215,0.001257,10,{'C': 10},0.874191,0.881380,0.863408,0.865564,0.861151,0.869139,0.007547,3
3,0.338605,0.008985,0.073295,0.003316,100,{'C': 100},0.873472,0.881380,0.863408,0.865564,0.861151,0.868995,0.007456,4
4,0.329366,0.007951,0.070202,0.002012,1000,{'C': 1000},0.873472,0.881380,0.863408,0.865564,0.861151,0.868995,0.007456,4

###Q5d RBF Kernel

Apply Linear SVM for costs (C) = [0.1, 1, 10, 100, 1000], predict for the test set and check f1 score for each of the costs. State the best cost

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
param_grid = {'C': [0.1, 1, 10, 100, 1000]} 
grid_search = GridSearchCV(estimator = classifier,
                           scoring='f1_micro',
                           param_grid = param_grid,
                           refit=2,
                           verbose=2)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ..............................................C=0.1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ................................................C=1; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ...............................................C=10; total time=   0.2s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END ..............................................C=100; total time=   0.4s
[CV] END .............................................C=1000; total time=   1.1s
[CV] END .............................................C=1000; total time=   1.0s
[CV] END .............................................C=1000; total time=   1.8s
[CV] END .............................................C=1000; total time=   1.5s
[CV] END .............................................C=1000; total time=   1.3s

GridSearchCV(estimator=SVC(random_state=0),
             param_grid={'C': [0.1, 1, 10, 100, 1000]}, refit=2,
             scoring='f1_micro', verbose=2)

In [24]:
pd.DataFrame(grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.167003,0.011127,0.049315,0.002512,0.1,{'C': 0.1},0.976276,0.979152,0.977714,0.971244,0.970504,0.974978,0.003480,5
1,0.144586,0.008736,0.037290,0.004190,1,{'C': 1},0.976995,0.982746,0.978433,0.974838,0.973381,0.977279,0.003239,3
2,0.171304,0.006793,0.033908,0.004074,10,{'C': 10},0.979871,0.982027,0.977714,0.976276,0.974820,0.978142,0.002561,1
3,0.338804,0.014868,0.031324,0.002922,100,{'C': 100},0.979871,0.982027,0.974838,0.975557,0.975540,0.977567,0.002856,2
4,1.322414,0.260155,0.036569,0.009727,1000,{'C': 1000},0.976276,0.982027,0.971244,0.976276,0.974820,0.976129,0.003476,4